### ISSUE TITLE
Uncaught Error: 4080D4A37F000000:error:0A0000F4:SSL routines:ssl3_read_bytes:unexpected message:../ssl/record/rec_layer_s3.c:1523:

### ISSUE THREAD

**Issue by Demon000** [Demon000/web-auto#121]
Uncaught Error: 4080D4A37F000000:error:0A0000F4:SSL routines:ssl3_read_bytes:unexpected message:../ssl/record/rec_layer_s3.c:1523:

    at DuplexSocket.ondata (node:internal/js_stream_socket:77:22)
    at DuplexSocket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at DuplexSocket._write (/home/demon000/web-auto/node_modules/native-duplexpair/index.js:24:22)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at file:///home/demon000/web-auto/node-common/dist/esm/crypto/NodeCryptor.js:97:40
Emitted 'error' event on TLSSocket instance at:
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by Demon000** [comment]
https://github.com/Demon000/web-auto/commit/3ee50993f43bd5909b288061e5c92213ec1476f2

Fixed already connected device detection.
