### ISSUE TITLE
Error: 40CC79504D700000:error:0A0000F4:SSL routines:ssl3_read_bytes:unexpected message:ssl/record/rec_layer_s3.c:802:

### ISSUE THREAD

**Issue by Demon000** [Demon000/web-auto#136]
```
node:events:497
      throw er; // Unhandled 'error' event
      ^

Error: 40CC79504D700000:error:0A0000F4:SSL routines:ssl3_read_bytes:unexpected message:ssl/record/rec_layer_s3.c:802:

    at DuplexSocket.ondata (node:internal/js_stream_socket:78:22)
    at DuplexSocket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at DuplexSocket._write (/home/demon000/projects/web-auto/node_modules/native-duplexpair/index.js:24:22)
    at writeOrBuffer (node:internal/streams/writable:564:12)
    at _write (node:internal/streams/writable:493:10)
    at Writable.write (node:internal/streams/writable:502:10)
    at file:///home/demon000/projects/web-auto/node-common/dist/esm/crypto/NodeCryptor.js:100:40
Emitted 'error' event on TLSSocket instance at:
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  library: 'SSL routines',
  reason: 'unexpected message',
  code: 'ERR_SSL_UNEXPECTED_MESSAGE'
}
```

**Comment by Demon000** [comment]
Happens if already connected device is not reset and is connected to again.
