### ISSUE TITLE
Fix import.meta.dirname on node18

### ISSUE THREAD

**Issue by Demon000** [Demon000/web-auto#177]
failed to load config from /home/analog/web-auto/web/vite.config.ts
error during build:
TypeError [ERR_INVALID_ARG_TYPE]: The "paths[0]" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:405:5)
    at validateString (node:internal/validators:162:11)
    at resolve (node:path:1097:7)
    at file:///home/analog/web-auto/config-loader/dist/esm/index.js:4:21
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:336:24)
    at async loadConfigFromBundledFile (file:///home/analog/web-auto/node_modules/vite/dist/node/chunks/dep-BKbDVx1T.js:69911:21)
    at async loadConfigFromFile (file:///home/analog/web-auto/node_modules/vite/dist/node/chunks/dep-BKbDVx1T.js:69764:28)
    at async resolveConfig (file:///home/analog/web-auto/node_modules/vite/dist/node/chunks/dep-BKbDVx1T.js:69367:28)
    at async build (file:///home/analog/web-auto/node_modules/vite/dist/node/chunks/dep-BKbDVx1T.js:68481:20)

**Comment by Demon000** [comment]
Recommended using nvm.
