### ISSUE TITLE
Fix unavailable event being fired before disconnect finishes

### ISSUE THREAD

**Issue by Demon000** [Demon000/web-auto#90]

**Comment by Demon000** [comment]
2024-01-02T02:29:48.774Z info [NodeAndroidAutoServer]     Device TCP: 192.168.1.5 no longer available
2024-01-02T02:30:03.798Z error [TcpDevice@192.168.1.5]    Failed to emit state updated event
AssertionError [ERR_ASSERTION]: false == true
    at NodeAndroidAutoServer.onDeviceStateUpdated (file:///home/demon000/projects/web-auto/android-auto/dist/esm/AndroidAutoServer.js:254:9)
    at TcpDevice.setState (file:///home/demon000/projects/web-auto/android-auto/dist/esm/transport/Device.js:40:25)
    at TcpDevice.connect (file:///home/demon000/projects/web-auto/android-auto/dist/esm/transport/Device.js:66:14)
    at async NodeAndroidAutoServer.connectDeviceAsync (file:///home/demon000/projects/web-auto/android-auto/dist/esm/AndroidAutoServer.js:405:13)
    at async NodeAndroidAutoServer.connectDeviceName (file:///home/demon000/projects/web-auto/node-common/dist/esm/NodeAndroidAutoServer.js:117:9)
    at async ElectronIpcServiceRegistry.handleMessageAsync (file:///home/demon000/projects/web-auto/common-ipc/dist/esm/main.js:196:32) {
  actual: false,
  code: 'ERR_ASSERTION',
  expected: true,
  generatedMessage: true,
  operator: '=='
}
2024-01-02T02:30:03.799Z info [NodeAndroidAutoServer]     Connected device TCP: 192.168.1.5
2024-01-02T02:30:03.800Z info [NodeAndroidAutoServer]     Starting dependencies
2024-01-02T02:30:03.800Z info [NodeAndroidAutoServer]     Starting cryptor
2024-01-02T02:30:03.801Z info [NodeAndroidAutoServer]     Started cryptor
2024-01-02T02:30:03.801Z info [NodeAndroidAutoServer]     Starting services
2024-01-02T02:30:03.801Z info [NodeAndroidAutoServer]     Started services
2024-01-02T02:30:03.801Z info [NodeAndroidAutoServer]     Starting control service
2024-01-02T02:30:03.801Z info [NodeAndroidAutoServer]     Started control service
2024-01-02T02:30:03.801Z info [NodeAndroidAutoServer]     Started dependencies
2024-01-02T02:30:03.801Z debug [ControlService]    Send version request
2024-01-02T02:30:08.805Z debug [ControlService]    Send PingRequest
{ timestamp: '1704162608805000' }
2024-01-02T02:30:08.806Z info [ControlService]     Aborted wait for message with id 2
2024-01-02T02:30:08.807Z error [NodeAndroidAutoServer]    Failed to do control service start
Error: Aborted
    at EventTarget.onAbort (file:///home/demon000/projects/web-auto/android-auto/dist/esm/services/Service.js:110:24)
    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:757:20)
    at EventTarget.dispatchEvent (node:internal/event_target:692:26)
    at abortSignal (node:internal/abort_controller:369:10)
    at Timeout._onTimeout (node:internal/abort_controller:126:7)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
2024-01-02T02:30:08.808Z info [NodeAndroidAutoServer]     Disconnecting device TCP: 192.168.1.5 with reason do-start-failed
2024-01-02T02:30:08.808Z info [NodeAndroidAutoServer]     Stopping dependencies
2024-01-02T02:30:08.808Z info [NodeAndroidAutoServer]     Stopping control service
2024-01-02T02:30:08.808Z info [NodeAndroidAutoServer]     Stopped control service
2024-01-02T02:30:08.808Z info [NodeAndroidAutoServer]     Stopping services
2024-01-02T02:30:08.809Z info [NodeAndroidAutoServer]     Stopped services
2024-01-02T02:30:08.809Z info [NodeAndroidAutoServer]     Stopping cryptor
2024-01-02T02:30:08.809Z info [NodeAndroidAutoServer]     Stopped cryptor
2024-01-02T02:30:08.810Z info [NodeAndroidAutoServer]     Stopped dependencies
2024-01-02T02:30:08.810Z info [TcpDevice@192.168.1.5]     Disconnecting with reason do-start-failed
2024-01-02T02:30:08.810Z error [TcpDevice@192.168.1.5]    Failed to emit state updated event
AssertionError [ERR_ASSERTION]: false == true
    at NodeAndroidAutoServer.onDeviceStateUpdated (file:///home/demon000/projects/web-auto/android-auto/dist/esm/AndroidAutoServer.js:254:9)
    at TcpDevice.setState (file:///home/demon000/projects/web-auto/android-auto/dist/esm/transport/Device.js:40:25)
    at TcpDevice.disconnect (file:///home/demon000/projects/web-auto/android-auto/dist/esm/transport/Device.js:89:14)
    at NodeAndroidAutoServer.disconnectDeviceInternal (file:///home/demon000/projects/web-auto/android-auto/dist/esm/AndroidAutoServer.js:446:26)
    at NodeAndroidAutoServer.connectDeviceAsync (file:///home/demon000/projects/web-auto/android-auto/dist/esm/AndroidAutoServer.js:429:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async NodeAndroidAutoServer.connectDeviceName (file:///home/demon000/projects/web-auto/node-common/dist/esm/NodeAndroidAutoServer.js:117:9)
    at async ElectronIpcServiceRegistry.handleMessageAsync (file:///home/demon000/projects/web-auto/common-ipc/dist/esm/main.js:196:32) {
  actual: false,
  code: 'ERR_ASSERTION',
  expected: true,
  generatedMessage: true,
  operator: '=='
}
2024-01-02T02:30:08.811Z info [TcpDevice@192.168.1.5]     Disconnecting transport
2024-01-02T02:30:08.811Z info [TcpDevice@192.168.1.5]     Disconnected transport
2024-01-02T02:30:08.811Z error [TcpDevice@192.168.1.5]    Failed to emit state updated event
AssertionError [ERR_ASSERTION]: false == true
    at NodeAndroidAutoServer.onDeviceStateUpdated (file:///home/demon000/projects/web-auto/android-auto/dist/esm/AndroidAutoServer.js:254:9)
    at TcpDevice.setState (file:///home/demon000/projects/web-auto/android-auto/dist/esm/transport/Device.js:40:25)
    at TcpDevice.disconnect (file:///home/demon000/projects/web-auto/android-auto/dist/esm/transport/Device.js:108:14)
    at async NodeAndroidAutoServer.disconnectDeviceInternal (file:///home/demon000/projects/web-auto/android-auto/dist/esm/AndroidAutoServer.js:446:13)
    at async NodeAndroidAutoServer.connectDeviceAsync (file:///home/demon000/projects/web-auto/android-auto/dist/esm/AndroidAutoServer.js:429:13)
    at async NodeAndroidAutoServer.connectDeviceName (file:///home/demon000/projects/web-auto/node-common/dist/esm/NodeAndroidAutoServer.js:117:9)
    at async ElectronIpcServiceRegistry.handleMessageAsync (file:///home/demon000/projects/web-auto/common-ipc/dist/esm/main.js:196:32) {
  actual: false,
  code: 'ERR_ASSERTION',
  expected: true,
  generatedMessage: true,
  operator: '=='
}
2024-01-02T02:30:08.812Z info [NodeAndroidAutoServer]     Disconnected device TCP: 192.168.1.5
2024-01-02T02:30:11.178Z info [NodeAndroidAutoServer]     New available device TCP: 192.168.1.5

**Comment by Demon000** [comment]
Add a device lock and use it when changing states?
